- name: Install postgresql (Debian)
  apt: name={{item}}
       state=present
       update_cache=yes
       cache_valid_time=86400
  with_items:
   - postgresql
   - postgresql-client
   - libpq-dev
   - python-psycopg2
